Repository SaveMeMungz/SaveMeMungz-Web, pull requests merged in 2024-10, with the labels that each got.

#3 Feat: 바텀탭 개발 및 전역폰트 설정
  .eslintrc.json
  .husky/pre-commit
  .prettierrc
  package-lock.json
  package.json
  src/app/(main)/home/page.js
  src/app/(main)/layout.js
  src/app/StyledLayout.js
  src/assets/fonts/GeistMonoVF.woff
  src/assets/fonts/GeistVF.woff
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/components/layout/.gitkeep
  src/components/layout/BottomTab.js
  src/components/layout/CustomHeader.js
  src/constants/font.js
  src/styles/globalStyles.js
Labels: ✨ Feature, :art: Style, :lipstick: UI

#6 Feat/#4 공통 컴포넌트 개발
  src/app/(auth)/login/page.jsx
  src/app/(auth)/sign-up/page.jsx
  src/app/(main)/course/page.js
  src/app/(main)/course/page.jsx
  src/app/(main)/help-mungz/page.js
  src/app/(main)/help-mungz/page.jsx
  src/app/(main)/home/info/page.js
  src/app/(main)/home/info/page.jsx
  src/app/(main)/home/mbti/page.js
  src/app/(main)/home/mbti/page.jsx
  src/app/(main)/home/page.js
  src/app/(main)/home/page.jsx
  src/app/(main)/layout.jsx
  src/app/(main)/mypage/edit/page.js
  src/app/(main)/mypage/edit/page.jsx
  src/app/(main)/mypage/page.js
  src/app/(main)/mypage/page.jsx
  src/app/StyledLayout.jsx
  src/app/layout.jsx
  src/app/match-info/page.jsx
  src/app/onboarding/page.jsx
  src/app/page.jsx
  src/app/providers.jsx
  src/components/common/.gitkeep
  src/components/common/CustomButton.jsx
  src/components/common/InfoBanner.jsx
  src/components/common/SectionDivider.jsx
  src/components/layout/BottomTab.jsx
  src/components/layout/CustomHeader.js
  src/components/layout/CustomHeader.jsx
  src/constants/colors.js
  src/constants/space.js
Labels: ✨ Feature, :art: Style, 🔨 Refactor

#8 Feat: splash 구현
  src/app/page.jsx
  src/assets/images/splash-logo.png
Labels: ✨ Feature, :lipstick: UI

#14 Build: Jira 설정
  .github/workflows/jira-sync.yml
  .husky/prepare-commit-msg
Labels: :building_construction: Build

#17 Build: Jira 추가 설정
  .github/workflows/jira-sync.yml
Labels: :building_construction: Build

#10 Feat: 마이페이지 UI 퍼블리싱
  src/app/(main)/layout.jsx
  src/app/(main)/mypage/SupportSection.jsx
  src/app/(main)/mypage/UserStats.jsx
  src/app/(main)/mypage/edit/page.jsx
  src/app/(main)/mypage/page.jsx
  src/assets/icons/chat-icon.png
  src/assets/icons/support-icon.png
  src/assets/icons/vector-icon.png
  src/assets/images/default-profile.png
  src/components/common/CustomButton.jsx
  src/components/common/CustomInput.jsx
  src/components/common/GreetingMessage.jsx
  src/constants/colors.js
Labels: ✨ Feature, :lipstick: UI

#19 Feat: 실종근황 퍼블리싱
  .github/workflows/jira-sync.yml
  src/app/(main)/help-mungz/ChartGraph.jsx
  src/app/(main)/help-mungz/page.jsx
  src/assets/images/tempLost.png
Labels: ✨ Feature, :lipstick: UI

#23 Feat: 지도UI 퍼블리싱
  .github/workflows/jira-sync.yml
  README.md
  src/app/(main)/course/FilterBarComponent.jsx
  src/app/(main)/course/MapView.jsx
  src/app/(main)/course/ShelterCardComponent.jsx
  src/app/(main)/course/page.jsx
  src/app/(main)/help-mungz/page.jsx
  src/app/(main)/layout.jsx
  src/app/(main)/mypage/page.jsx
  src/assets/images/tempShelter.png
Labels: ✨ Feature, 📬 API, :lipstick: UI

#25 Feat: 멍즈찾기 UI개발
  package-lock.json
  package.json
  src/api/home/index.jsx
  src/app/(main)/home/DogProfile.jsx
  src/app/(main)/home/info/page.jsx
  src/app/(main)/home/mbti/MbtiMatch.jsx
  src/app/(main)/home/mbti/page.jsx
  src/app/(main)/home/page.jsx
  src/assets/images/비숑 임시 사진.svg
  src/assets/images/웰시코기 임시 사진.svg
Labels: 📬 API, :lipstick: UI

#27 Refactor: 홈화면 리팩토링
  .prettierrc
  next.config.mjs
  src/api/home/index.js
  src/api/home/index.jsx
  src/app/(auth)/login/components/.gitkeep
  src/app/(auth)/sign-up/components/.gitkeep
  src/app/(main)/course/components/FilterBarComponent.jsx
  src/app/(main)/course/components/MapView.jsx
  src/app/(main)/course/components/ShelterCardComponent.jsx
  src/app/(main)/course/page.jsx
  src/app/(main)/help-mungz/components/ChartGraph.jsx
  src/app/(main)/help-mungz/page.jsx
  src/app/(main)/home/DogProfile.jsx
  src/app/(main)/home/components/CustomTag.jsx
  src/app/(main)/home/components/MbtiMatchComponent.jsx
  src/app/(main)/home/components/MungzProfileCard.jsx
  src/app/(main)/home/info/page.jsx
  src/app/(main)/home/mbti/MbtiMatch.jsx
  src/app/(main)/home/mbti/page.jsx
  src/app/(main)/home/page.jsx
  src/app/(main)/mypage/components/SupportSection.jsx
  src/app/(main)/mypage/components/UserStats.jsx
  src/app/(main)/mypage/page.jsx
  src/app/onboarding/components/.gitkeep
  src/assets/images/sparkle.png
  src/assets/images/temp/tempLost.png
  src/assets/images/temp/tempMungz1.png
  src/assets/images/temp/tempMungz2.png
  src/assets/images/temp/tempShelter.png
  src/assets/images/비숑 임시 사진.svg
  src/assets/images/웰시코기 임시 사진.svg
  src/utils/dataProcessors.js
  src/utils/formatters.js
Labels: :art: Style, :lipstick: UI, 🔨 Refactor

#34 Fix: Main브랜치 변경사항 Dev에 최신화
  .github/workflows/jira-sync.yml
  .github/workflows/sync-jira-on-close.yml
Labels: 🐞 BugFix
